input_number:
  peak_summer_price:
    name: "peak_summer_price"
    initial: 0.21
    min: 0
    max: 0.50
    step: 0.01
    unit_of_measurement: "USD/kWh"
    mode: box
  peak_off_summer_price:
    name: "peak_off_summer_price"
    initial: 0.16
    min: 0
    max: 0.50
    step: 0.01
    unit_of_measurement: "USD/kWh"
    mode: box
  off_peak_price:
    name: "off_peak_price"
    initial: 0.04
    min: 0
    max: 0.50
    step: 0.01
    unit_of_measurement: "USD/kWh"
    mode: box