alias: Peak Automation Off-peak End Non-Summer
description: ""
trigger:
  - platform: time
    at: input_datetime.off_peak_energy_end
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ (now().month < 6 or now().month > 9) and now().weekday() < 5 }}"
        alias: Is it an off-summer weekday?
      - condition: template
        value_template: >-
          {{ not (now().month == 1 and now().day == 1) and not (now().month ==
          12 and now().day == 25) }}
        alias: Is it not New Years Day or Christmas Day?
      - condition: template
        value_template: >-
          {{ not (now().month == 9 and now().weekday() == 0 and now().day < 8) 
          }}
        alias: Is it not Labor day?
      - condition: template
        value_template: >-
          {{ not (now().month == 11 and now().weekday() == 3 and now().day >= 23
          and now().day != 30) }}
        alias: Is it not Thanksgiving day?
      - condition: template
        value_template: >-
          {{ not (now().month == 5 and now().weekday() == 0 and now().day >=
          24)  }}
        alias: Is it not Memorial day?
    alias: Is it a valid peak day?
action:
  - service: select.select_option
    data:
      option: peakoffsummer
    target:
      entity_id: select.xcel_energy_grid
mode: single
